### PR TITLE
Drive Subsystem and Commands

### LINKED ISSUE #2: Drive Subsystem and Commands

### PR DESCRIPTION
**Pull request by salvobonsma**

### CODE REVIEW

**Review by Saturncorgi — APPROVED** [review]

**Review by Penguin114 — APPROVED** [review]
1

**Review by a-mishmash — APPROVED** [review]
👍

**Review by Amber-leaf — APPROVED** [review]

**Review by ryanelbert5125gmail — APPROVED** [review]
looks fine

**Review by sylth — APPROVED** [review]
good job :)

**Review by Dar1ngit — DISMISSED** [review]
Good

**Review by jennyhguo — APPROVED** [review]

**Comment by Amber-leaf** [comment]
> Good

pdsoifhb

**Review by 1rkgrissom — APPROVED** [review]

**Pull request merged**
